name: Prod PR Check

on:
  workflow_call: {}

jobs:
  check-prod-pr-branch:
    name: "Branch check"
    if: github.base_ref == 'prod'
    runs-on: ubuntu-latest
    steps:
      - name: Check Prod PR Branch
        run: |
          if [[ ${{github.head_ref}} != mpt ]]; 
          then
             echo "Error: Pull request to prod must come from 'mpt' branch"
             exit 1
          fi
