name: Test Terraform PR Workflow

on:
  workflow_dispatch: {}
  pull_request:
    branches:
    - main

jobs:
  sandbox:
    uses: ./.github/workflows/terraform-plan.yml
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
    with:
      terraform_version: 1.6.1
      terraform_path: terraform-workflows-test
      environment: sandbox
      account_number: 743078781022
  sdlc:
    uses: ./.github/workflows/terraform-plan.yml
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
    with:
      terraform_version: 1.6.1
      terraform_path: terraform-workflows-test
      environment: sdlc
      account_number: 139383360831
  prod:
    uses: ./.github/workflows/terraform-plan.yml
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
    with:
      terraform_version: 1.6.1
      terraform_path: terraform-workflows-test
      environment: prod
      account_number: 162850226511
  pr-comment:
    uses: ./.github/workflows/terraform-publish-plan-on-pr.yml
    secrets: inherit
    needs:
    - sandbox
    - sdlc
    - prod
    with:
      environments: sandbox,sdlc,prod

